"""Added email to USERS and last_seen to DeviceInformation

Revision ID: cee2aec81690
Revises: 
Create Date: 2025-04-03 16:00:55.156676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee2aec81690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otps')
    op.drop_index('ix_pins_id', table_name='pins')
    op.drop_table('pins')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('phone_id', sa.VARCHAR(), nullable=False),
    sa.Column('car_reg', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('pins',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('pin', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pins_id', 'pins', ['id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('phone_id', sa.VARCHAR(), nullable=False),
    sa.Column('otp', sa.VARCHAR(), nullable=False),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['users.phone_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
